workspace:
  base: /go
  path: src/github.com/casualjim/drone-sandbox

pipeline:
  envcheck:
    environment:
      DOCKER_HOST: tcp://127.0.0.1:2375
    image: docker:latest
    pull: true
    commands:
      - env
      - docker ps
      - docker images

  compile:
    environment:
      DOCKER_HOST: tcp://127.0.0.1:2375
    image: golang:1.7
    pull: true
    commands:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo


  docker:
    image: casualjim/drone-docker
    privileged: true
    repo: casualjim/drone-sandbox
    dockerfile: ./Dockerfile
    force_tag: true
    build_args:
      - "version=${DRONE_TAG}"
      - "channel=stable"
      - "commit=${DRONE_COMMIT}"
    tag:
      - stable
      - latest
      - "${DRONE_TAG}"
    when:
      event: tag
      branch: master

services:
  dind:
    image: docker:1.12-dind
    privileged: true
    pull: true
